### ISSUE TITLE
Make the compiler accept files via arguments 

### ISSUE THREAD

**Issue by Grillo-0** [vinumdoc/vinum#12]
Currently, `vinumc` only accepts code via stdin. For usability, it would better to pass the file via arguments (i.e. `vinumc doc.vin`)

**Comment by artP2** [comment]
Would accepting a single file be enough?

**Comment by Grillo-0** [comment]
> Would accepting a single file be enough?

For now, it is. I don't think we have the infrastructure to deal with multiple files yet.
